dist: trusty
language: rust
services: docker
sudo: required

os:
  - linux
  - osx

before_install:
  - set -e
  - rustup self update

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sh ci/install.sh; fi
  - if [[ $TRAVIS_OS_NAME == "osx"   ]]; then rustup target add i686-apple-darwin; fi

script:
  - make test
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then make release_lnx; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then make release_win; fi
  - if [[ $TRAVIS_OS_NAME == "osx"   ]]; then make release_mac; fi

after_success: |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
        RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
        # Uncomment the following line for coveralls.io
        # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

        # Uncomment the following two lines create and upload a report for codecov.io
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
    fi

deploy:
  provider: releases
  api_key:
    secure: LqfHs6YH1Y+CHLipi07PUr05ONL6BZ1qYdn2TL+5Cf46+UvYBp5Olwyt8BqoxLVWj96wuKupczv1zGwrTdxxGjT/8KYDN/FFTzaCXDIIvJl3CqA0g5RqWtNH3uf7e5xBNpeyTqOdZrKTKVTe8ay7EGiqS4z+LqnC1FSAEm9alrHIjmqqp6Vln9csMTN1yHfRGv4iTSjrh+RmGlG3uQEu/IR6UtCkwfqqgTqgCqf2XF0xU4I1aSUCQ/Ubl18dtvfhQ56p0Xs3I8V4e7yTVvNNtqgXSfMieNF/qreNw6VjC855HeJ+LYgI1rbfuUT6dQYOkZVLswBWmM3bQnlG+6nvGht8G44G80Lznn/iW+KBAtO+1KFZp+GawuE0BgobMYxKO4n2BuhUcH9PzGmekzB1Vb/uwURZYy6bbyORPUcfeGO+dqVHzNdY7rG+/OhQz3+RmyKamlOdVYoeN1B1z4tu/VhY7+149uGnf/sZeU5DfBVUCE8+ug56iT5iaRkPCifC6WlqOKrNlfBbE/Q8YKclitui2NQrYeLbJgwIAn54IhdYCx3wXCqrqm16DDtUWEWIr+5xxMJhD2UFvb49ZX4LszStJX+CS9GtIpMTBsnGZCq2fS1/QI0F5GCP+PQ/ULaQakGWHbVTarvqrZMqGAGBm1666+nOJmE3ZBbswRIhpGI=
  file:
    - gip-*.zip
  file_glob: true
  skip_cleanup: true
  on:
    repo: dalance/gip
    tags: true
