sudo: required
dis: trusty

language: rust

os:
- linux
- osx

env:
- ARCH=i686
- ARCH=x86_64

rust: stable

before_install:
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -qq update; fi
- if [[ $TRAVIS_OS_NAME == "linux" && $ARCH == "i686"   ]]; then sudo apt-get install -y gcc-multilib g++-multilib libssl-dev:i386 binutils-mingw-w64-i686 gcc-mingw-w64-i686; fi
- if [[ $TRAVIS_OS_NAME == "linux" && $ARCH == "x86_64" ]]; then sudo apt-get install -y gcc-multilib g++-multilib gcc-mingw-w64-x86-64; fi

before_script:
- curl https://sh.rustup.rs -sSf | sh -s -- -y
- export PATH=~/.cargo/bin:$PATH
- if [[ $TRAVIS_OS_NAME == "linux" && $ARCH == "x86_64" ]]; then rustup target add x86_64-pc-windows-gnu; fi
- if [[ $TRAVIS_OS_NAME == "linux" && $ARCH == "i686"   ]]; then rustup target add i686-unknown-linux-gnu; fi
- if [[ $TRAVIS_OS_NAME == "linux" && $ARCH == "i686"   ]]; then rustup target add i686-pc-windows-gnu; fi
- if [[ $TRAVIS_OS_NAME == "osx"   && $ARCH == "i686"   ]]; then rustup target add i686-apple-darwin; fi
- which cargo
- which rustc
- cargo --version
- rustc --version

script:
- if [[ $TRAVIS_OS_NAME == "osx"   && $ARCH == "x86_64" ]]; then make test; fi
- if [[ $TRAVIS_OS_NAME == "linux" && $ARCH == "x86_64" ]]; then make test; fi
- if [[ $TRAVIS_OS_NAME == "osx"   && $ARCH == "i686"   ]]; then make release_osx32; fi
- if [[ $TRAVIS_OS_NAME == "osx"   && $ARCH == "x86_64" ]]; then make release_osx64; fi
- if [[ $TRAVIS_OS_NAME == "linux" && $ARCH == "i686"   ]]; then make release_lnx32; make release_win32; fi
- if [[ $TRAVIS_OS_NAME == "linux" && $ARCH == "x86_64" ]]; then make release_lnx64; make release_win64; fi

deploy:
  provider: releases
  api_key:
    secure: OYFSyoPf6gAXGZoHs/lAAgyZHHwOhmtlzPGAnuFRJuRPTMvt3ck5DkH6+KtNOjdlM8mmF7gdXJyVJeQcbBufemJaMs1PsApu49e4sQQhv57P07+w5WOL9KVl5avZyXslMsdNGb7VmAhYgAbErC2VAvKakEL5y/PO/St5HwN/1130qn9Hbvd5XZKceEQBBKZ/rZehtI+4FKy2OvDOL3R8RpV7b+XgSCor9Zz4mtkdKv5yteuggRK6b8WPQukkCs2rHyK4rashjP4MeqIwYSUu13sDBXij4MQ3rM6cc5+Spk5lxzmwvjUir8O0rrIg2Sd6J4m9aHgjBk1i/BH6MDRXAlqSqhgiU2plPGN9VUy1Nvr0yd7A28Zv3tcAwlDaYaEIXEN1O/YK4IKgj/IWpEtHznQ4afbVvKCmmsE1GdfnHuj4v4E5yn76SwZCZvXE+ouU1n/UtxN9zpiPgzhECq+2kIcAS6xqdgrZGP/ujzqWVuUYvAtwDcDBGFa7JR+d4mYbGBmXjitX+Mm1sRQPQL6XgPxRdkQMqVdqZXCQp8xtL9Lg1Dh+IfbByK5popDxwHlddjaaDMCzdTQ85aW0mjnm5JFRlQZdlE2mP7EWHypG+SRgB3//MgabmFSH2Fs231vnsjADktE6s+6eJp83WNQCWdwi2S6VbcNkeVpf/86Rj7Y=
  file:
    - gip-*.zip
  file_glob: true
  skip_cleanup: true
  on:
    repo: dalance/gip
    tags: true
