language: rust

os:
- linux
- osx

before_script:
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then rustup target add x86_64-unknown-linux-musl; fi
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then rustup target add x86_64-pc-windows-gnu; fi
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -qq update; fi
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -qq install gcc-mingw-w64-x86-64 musl-tools libssl-dev; fi

script:
- make test
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then make release_lnx; fi
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then make release_win; fi
- if [[ $TRAVIS_OS_NAME == "osx"   ]]; then make release_mac; fi

after_success: |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
        bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
        # Uncomment the following line for coveralls.io
        # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

        # Uncomment the following two lines create and upload a report for codecov.io
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
    fi

deploy:
  provider: releases
  api_key:
    secure: OYFSyoPf6gAXGZoHs/lAAgyZHHwOhmtlzPGAnuFRJuRPTMvt3ck5DkH6+KtNOjdlM8mmF7gdXJyVJeQcbBufemJaMs1PsApu49e4sQQhv57P07+w5WOL9KVl5avZyXslMsdNGb7VmAhYgAbErC2VAvKakEL5y/PO/St5HwN/1130qn9Hbvd5XZKceEQBBKZ/rZehtI+4FKy2OvDOL3R8RpV7b+XgSCor9Zz4mtkdKv5yteuggRK6b8WPQukkCs2rHyK4rashjP4MeqIwYSUu13sDBXij4MQ3rM6cc5+Spk5lxzmwvjUir8O0rrIg2Sd6J4m9aHgjBk1i/BH6MDRXAlqSqhgiU2plPGN9VUy1Nvr0yd7A28Zv3tcAwlDaYaEIXEN1O/YK4IKgj/IWpEtHznQ4afbVvKCmmsE1GdfnHuj4v4E5yn76SwZCZvXE+ouU1n/UtxN9zpiPgzhECq+2kIcAS6xqdgrZGP/ujzqWVuUYvAtwDcDBGFa7JR+d4mYbGBmXjitX+Mm1sRQPQL6XgPxRdkQMqVdqZXCQp8xtL9Lg1Dh+IfbByK5popDxwHlddjaaDMCzdTQ85aW0mjnm5JFRlQZdlE2mP7EWHypG+SRgB3//MgabmFSH2Fs231vnsjADktE6s+6eJp83WNQCWdwi2S6VbcNkeVpf/86Rj7Y=
  file:
    - gip-*.zip
  file_glob: true
  skip_cleanup: true
  on:
    repo: dalance/gip
    tags: true
