branches:
    except:
        - gh-pages

platform:
    - x64

environment:
    matrix:
        - TARGET: i686-pc-windows-msvc
          ARCH: i686
        - TARGET: x86_64-pc-windows-msvc
          ARCH: x86_64

install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe -y
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - if NOT "%TARGET%" == "x86_64-pc-windows-msvc" rustup target add %TARGET%

build_script:
    - cmd: cargo build --release --target=%TARGET%

after_build:
    - cmd: 7z a gip-%APPVEYOR_REPO_TAG_NAME%-%ARCH%-win.zip %APPVEYOR_BUILD_FOLDER%\target\%TARGET%\release\gip.exe

artifacts:
    - path: gip*.zip
      name: gip

deploy:
    provider: GitHub
    auth_token:
        secure: YwL0NwyM+vym8U4Gxc8hbOEZ4+MHe6gMzTc9FebvvIoB3VLGSs7t4JtXQxiJixl9
    artifact: /.*\.zip/
    on:
        branch: /v\d+\.\d+\.\d+/
        appveyor_repo_tag: true
