branches:
    except:
        - gh-pages

platform:
    - x64

environment:
    RUST_INSTALL_DIR: C:\Rust
    matrix:
        - RUST_INSTALL_TRIPLE: i686-pc-windows-msvc
          RUST_VERSION: 1.6.0
          ARCH: i686
          OPENSSL_ARCH: Win32
          OPENSSL_LIB_DIR: C:\OpenSSL-Win32\lib\VC
          OPENSSL_LIBS: ssleay32MT:libeay32MT
          OPENSSL_INCLUDE_DIR: C:\OpenSSL-Win32\include
          DEP_OPENSSL_INCLUDE_DIR: C:\OpenSSL-Win32\include
        - RUST_INSTALL_TRIPLE: x86_64-pc-windows-msvc
          RUST_VERSION: 1.6.0
          ARCH: x86_64
          OPENSSL_ARCH: Win64
          OPENSSL_LIB_DIR: C:\OpenSSL-Win64\lib\VC
          OPENSSL_LIBS: ssleay32MT:libeay32MT
          OPENSSL_INCLUDE_DIR: C:\OpenSSL-Win64\include
          DEP_OPENSSL_INCLUDE_DIR: C:\OpenSSL-Win64\include

install:
    - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:RUST_INSTALL_TRIPLE}.exe"
    - cmd: rust-%RUST_VERSION%-%RUST_INSTALL_TRIPLE%.exe /VERYSILENT /NORESTART /DIR="%RUST_INSTALL_DIR%"
    - cmd: SET PATH=%PATH%;%RUST_INSTALL_DIR%\bin
    - ps: Start-FileDownload "http://slproweb.com/download/${env:OPENSSL_ARCH}OpenSSL-1_0_2f.exe"
    - ps: Start-Process "${env:OPENSSL_ARCH}OpenSSL-1_0_2f.exe" -ArgumentList "/silent /verysilent /sp- /suppressmsgboxes" -Wait

build_script:
    - cmd: cargo build --release --target=%RUST_INSTALL_TRIPLE%

after_build:
    - cmd: 7z a gip-%APPVEYOR_REPO_TAG_NAME%-%ARCH%-win.zip %APPVEYOR_BUILD_FOLDER%\target\%RUST_INSTALL_TRIPLE%\release\gip.exe

artifacts:
    - path: gip*.zip
      name: gip

deploy:
    provider: GitHub
    auth_token:
        secure: YwL0NwyM+vym8U4Gxc8hbOEZ4+MHe6gMzTc9FebvvIoB3VLGSs7t4JtXQxiJixl9
    artifact: /.*\.zip/
    on:
        branch: /v\d+\.\d+\.\d+/
        appveyor_repo_tag: true
